bh2017/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^addArtist/', views.addArtist, name='addArtist'),
    url(r'^thankyou/', views.thankyou, name='thankyou'),
    url(r'^mailCheck/$', views.mailCheck, name='mailCheck'),
    url(r'^registration/$', views.registration, name='registration'),
    url(r'^tasks/$', views.tasks, name='tasks'),
    url(r'^prizes/$', views.prizes, name='prizes'),
    url(r'^rules/$', views.rules, name='rules'),
    url(r'^jury/$', views.jury, name='jury'),
    url(r'^sponsors/$', views.sponsors, name='sponsors'),
    url(r'^partners/$', views.partners, name='partners'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^forgetpass/$', views.forgetpass, name='forgetpass'),
    url(r'^login/', views.loginAuth, name='loginAuth'),
    url(r'^login_gallerys/', views.login_gallerys, name='login_gallerys'),
    url(r'^logoutArtist', views.logoutArtist, name='logoutArtist'),
    url(r'^loginFail', views.loginFail, name='loginFail'),
    url(r'^fullArtistAdd', views.fullArtistAdd, name='fullArtistAdd'),
    url(r'^cabinet', views.cabinet, name='cabinet'),
    url(r'^changeArtist', views.changeArtist, name='changeArtist'),
    url(r'^changePassword', views.changePassword, name='changePassword'),
    url(r'^restore', views.restore, name='restore'),
    url(r'^resetPass', views.resetPass, name='resetPass'),
    url(r'^errorpass', views.errorpass, name='errorpass'),
    url(r'^message/$', views.message, name='message'),
    url(r'^loadmorepartner/$', views.loadmorepartner, name='loadmorepartner'),
    url(r'^loadImg1', views.loadImg1, name='loadImg1'),
    url(r'^deleteImg1', views.deleteImg1, name='deleteImg1'),
    url(r'^loadImg2', views.loadImg2, name='loadImg2'),
    url(r'^deleteImg2', views.deleteImg2, name='deleteImg2'),
    url(r'^loadImg3', views.loadImg3, name='loadImg3'),
    url(r'^deleteImg3', views.deleteImg3, name='deleteImg3'),
    url(r'^loadImg4', views.loadImg4, name='loadImg4'),
    url(r'^deleteImg4', views.deleteImg4, name='deleteImg4'),
    url(r'^loadImg5', views.loadImg5, name='loadImg5'),
    url(r'^deleteImg5', views.deleteImg5, name='deleteImg5'),
    url(r'^loadImg6', views.loadImg6, name='loadImg6'),
    url(r'^deleteImg6', views.deleteImg6, name='deleteImg6'),
    url(r'^loadImg7', views.loadImg7, name='loadImg7'),
    url(r'^deleteImg7', views.deleteImg7, name='deleteImg7'),
    url(r'^loginJury', views.loginJury, name='loginJury'),
    url(r'^AuthJury', views.AuthJury, name='AuthJury'),
    url(r'^gallery1/$', views.gallery1, name='gallery1'),
    url(r'^gallery2/$', views.gallery2, name='gallery2'),
    url(r'^gallery3/$', views.gallery3, name='gallery3'),
    url(r'^gallery4/$', views.gallery4, name='gallery4'),
    url(r'^gallery5/$', views.gallery5, name='gallery5'),
    url(r'^gallery6/$', views.gallery6, name='gallery6'),
    url(r'^gallery7/$', views.gallery7, name='gallery7'),
    url(r'^final_gallery/$', views.final_gallery, name='final_gallery'),
    url(r'^com_gallery1/$', views.com_gallery1, name='com_gallery1'),
    url(r'^com_gallery2/$', views.com_gallery2, name='com_gallery2'),
    url(r'^com_gallery3/$', views.com_gallery3, name='com_gallery3'),
    url(r'^com_gallery4/$', views.com_gallery4, name='com_gallery4'),
    url(r'^com_gallery5/$', views.com_gallery5, name='com_gallery5'),
    url(r'^com_gallery6/$', views.com_gallery6, name='com_gallery6'),
    url(r'^com_gallery7/$', views.com_gallery7, name='com_gallery7'),
    url(r'^vote1/(?P<paint_id>[0-9]+)/$', views.vote1, name='vote1'),
    url(r'^remVote1/(?P<paint_id>[0-9]+)/$', views.remVote1, name='remVote1'),
    url(r'^vote2/(?P<paint_id>[0-9]+)/$', views.vote2, name='vote2'),
    url(r'^remVote2/(?P<paint_id>[0-9]+)/$', views.remVote2, name='remVote2'),
    url(r'^vote3/(?P<paint_id>[0-9]+)/$', views.vote3, name='vote3'),
    url(r'^remVote3/(?P<paint_id>[0-9]+)/$', views.remVote3, name='remVote3'),
    url(r'^vote4/(?P<paint_id>[0-9]+)/$', views.vote4, name='vote4'),
    url(r'^remVote4/(?P<paint_id>[0-9]+)/$', views.remVote4, name='remVote4'),
    url(r'^vote5/(?P<paint_id>[0-9]+)/$', views.vote5, name='vote5'),
    url(r'^remVote5/(?P<paint_id>[0-9]+)/$', views.remVote5, name='remVote5'),
    url(r'^vote6/(?P<paint_id>[0-9]+)/$', views.vote6, name='vote6'),
    url(r'^remVote6/(?P<paint_id>[0-9]+)/$', views.remVote6, name='remVote6'),
    url(r'^vote7/(?P<paint_id>[0-9]+)/$', views.vote7, name='vote7'),
    url(r'^remVote7/(?P<paint_id>[0-9]+)/$', views.remVote7, name='remVote7'),
    url(r'^com_gallerys', views.com_gallerys, name='com_gallerys'),
    url(r'^com_vote1/(?P<paint_id>[0-9]+)/$', views.com_vote1, name='com_vote1'),
    url(r'^com_remVote1/(?P<paint_id>[0-9]+)/$', views.com_remVote1, name='com_remVote1'),
    url(r'^com_vote2/(?P<paint_id>[0-9]+)/$', views.com_vote2, name='com_vote2'),
    url(r'^com_remVote2/(?P<paint_id>[0-9]+)/$', views.com_remVote2, name='com_remVote2'),
    url(r'^com_vote3/(?P<paint_id>[0-9]+)/$', views.com_vote3, name='com_vote3'),
    url(r'^com_remVote3/(?P<paint_id>[0-9]+)/$', views.com_remVote3, name='com_remVote3'),
    url(r'^com_vote4/(?P<paint_id>[0-9]+)/$', views.com_vote4, name='com_vote4'),
    url(r'^com_remVote4/(?P<paint_id>[0-9]+)/$', views.com_remVote4, name='com_remVote4'),
    url(r'^com_vote5/(?P<paint_id>[0-9]+)/$', views.com_vote5, name='com_vote5'),
    url(r'^com_remVote5/(?P<paint_id>[0-9]+)/$', views.com_remVote5, name='com_remVote5'),
    url(r'^com_vote6/(?P<paint_id>[0-9]+)/$', views.com_vote6, name='com_vote6'),
    url(r'^com_remVote6/(?P<paint_id>[0-9]+)/$', views.com_remVote6, name='com_remVote6'),
    url(r'^com_vote7/(?P<paint_id>[0-9]+)/$', views.com_vote7, name='com_vote7'),
    url(r'^com_remVote7/(?P<paint_id>[0-9]+)/$', views.com_remVote7, name='com_remVote7'),
    url(r'^final_vote/(?P<paint_id>[0-9]+)/$', views.final_vote, name='final_vote'),
    url(r'^final_remVote/(?P<paint_id>[0-9]+)/$', views.final_remVote, name='final_remVote'),
    url(r'^sertificat/$', views.sertificat, name='sertificat'),
]

bitvahudojnikov/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bh2017.urls', namespace='bh2017')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bh2017/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import (HttpResponse, HttpResponseForbidden,
                         HttpResponseRedirect)
from django.core.urlresolvers import reverse
from models import Artist, Partner, Jury, Tasks, Task_1, Task_6, Task_7, Task_3, Task_5, Task_2, Task_4, Vote
from forms import ArtistForm, UserAuth, registrationFull, changePersonal, passwordChange, forgetPass, loadArt1, loadArt2, loadArt3, loadArt4, loadArt5, loadArt6, loadArt7, JuryAuth
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger
from django.contrib.auth import authenticate,login, logout
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.db import IntegrityError
from django.template import RequestContext
from django.contrib.auth.decorators import login_required

from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse

from django.template.loader import get_template

from weasyprint import HTML, CSS

from django.conf import settings

def index(request):
    form = ArtistForm()
    formAuth = UserAuth()
    obj = Partner.objects.all()
    paginator = Paginator(obj, 12)
    page = request.GET.get('page')
    #print request.user
    fullName = 0
    if not request.user.is_anonymous():
            fullName = Artist.objects.filter(user=request.user)
            fullName = fullName[0].name

    try:
        documents = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        documents = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        documents = paginator.page(paginator.num_pages)
    return render(request, 'bh2017/index.html', {'form': form, 'documents': documents, 'formAuth': formAuth, 'Artist': fullName})

def thankyou(request):
    form = ArtistForm()
    formAuth = UserAuth()
    obj = Partner.objects.all()
    paginator = Paginator(obj, 12)
    page = request.GET.get('page')
    print request.user
    fullName = 0
    if not request.user.is_anonymous():
                fullName = Artist.objects.filter(user=request.user)
                fullName = fullName[0].name
    try:
        documents = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        documents = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        documents = paginator.page(paginator.num_pages)
    return render(request, 'bh2017/thankyou.html', {'form': form, 'documents': documents, 'formAuth': formAuth, 'Artist': fullName})

def addArtist(request):
    if request.method == 'POST':
        form = ArtistForm(request.POST, request.FILES)
        if form.is_valid():
            password1 = User.objects.make_random_password()
            try:
                user = User.objects.create_user(form.data['email'], form.data['email'], password1)
            except IntegrityError:
                return HttpResponseRedirect(reverse('bh2017:message'))
            form.age=0
            profile = form.save(commit=False)
            if profile.user_id is None:
                profile.user_id = user.id
                message = "Поздравляем! Вы успешно зарегистрировались на сайте проекта Битва художников! Ваш пароль: " + password1
            profile.save()
            send_mail(
                'Registration',
                message,
                'robot@bitvahudojnikov.ru',
                [form.data['email']],
                fail_silently=False,
            )
            return HttpResponseRedirect(reverse('bh2017:thankyou'))
    else:
        form = ArtistForm()
    return render(request, 'bh2017/index.html', {'form': form})

@csrf_exempt
def mailCheck(request):
    #print "ok"
    email = request.POST.get('email')
    data = True
    if User.objects.filter(username=email).exists():
        data = False
    return HttpResponse(data)

def registration(request):
    formAuth = UserAuth()
    regForm = registrationFull(initial={ 'age': 'Ваш возраст' })
    obj = Partner.objects.all()
    paginator = Paginator(obj, 12)
    page = request.GET.get('page')
    fullName = 0
    if not request.user.is_anonymous():
            fullName = Artist.objects.filter(user=request.user)
            fullName = fullName[0].name
    try:
        documents = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        documents = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        documents = paginator.page(paginator.num_pages)
    return render(request, 'bh2017/registration.html', {'documents': documents, 'regForm': regForm, 'formAuth': formAuth, 'Artist': fullName})

def tasks(request):
    formAuth = UserAuth()
    obj = Partner.objects.all()
    paginator = Paginator(obj, 12)
    page = request.GET.get('page')
    fullName = None
    loadArt_1 = loadArt1()
    loadArt_2 = loadArt2()
    loadArt_3 = loadArt3()
    loadArt_4 = loadArt4()
    loadArt_5 = loadArt5()
    loadArt_6 = loadArt6()
    loadArt_7 = loadArt7()
    tasks1 = None
    task_1 = None
    task_2 = None
    task_3 = None
    task_4 = None
    task_5 = None
    task_6 = None
    task_7 = None
    if not request.user.is_anonymous():
        fullName = Artist.objects.filter(user=request.user)
        fullName = fullName[0].name
    	tasks1 = Tasks.objects.all()
    	task_1 = Task_1.objects.filter(artist1=request.user)
    	task_2 = Task_2.objects.filter(artist1=request.user)
    	task_3 = Task_3.objects.filter(artist1=request.user)
    	task_4 = Task_4.objects.filter(artist1=request.user)
    	task_5 = Task_5.objects.filter(artist1=request.user)
    	task_6 = Task_6.objects.filter(artist1=request.user)
    	task_7 = Task_7.objects.filter(artist1=request.user)
    #print task_1
    if not request.user.is_anonymous():
         fullName = Artist.objects.filter(user=request.user)
         fullName = fullName[0].name

    try:
        documents = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        documents = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        documents = paginator.page(paginator.num_pages)
    return render(request, 'bh2017/tasks.html', {'documents': documents, 'formAuth': formAuth, 'Artist': fullName, 'tasks': tasks1, 'task_1': task_1, 'task_2': task_2, 'task_3': task_3, 'task_4': task_4, 'task_5': task_5, 'task_6': task_6, 'task_7': task_7, 'loadArt_1': loadArt_1, 'loadArt_2': loadArt_2, 'loadArt_3': loadArt_3, 'loadArt_4': loadArt_4, 'loadArt_5': loadArt_5, 'loadArt_6': loadArt_6, 'loadArt_7': loadArt_7})

def prizes(request):
    formAuth = UserAuth()
    obj = Partner.objects.all()
    paginator = Paginator(obj, 12)
    page = request.GET.get('page')
    # print request.user
    fullName = 0
    if not request.user.is_anonymous():
      	 fullName = Artist.objects.filter(user=request.user)
       	 fullName = fullName[0].name
    try:
        documents = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        documents = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        documents = paginator.page(paginator.num_pages)
    return render(request, 'bh2017/prizes.html', {'documents': documents, 'formAuth': formAuth, 'Artist': fullName})

def rules(request):
    formAuth = UserAuth()
    obj = Partner.objects.all()
    paginator = Paginator(obj, 12)
    page = request.GET.get('page')
    # print request.user
    fullName = 0
    if not request.user.is_anonymous():
            fullName = Artist.objects.filter(user=request.user)
            fullName = fullName[0].name
    try:
        documents = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        documents = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        documents = paginator.page(paginator.num_pages)
    return render(request, 'bh2017/rules.html',{'documents': documents, 'formAuth': formAuth, 'Artist': fullName})

def jury(request):
    formAuth = UserAuth()
    obj = Partner.objects.all()
    paginator = Paginator(obj, 12)
    page = request.GET.get('page')
    jurys = Jury.objects.all()
    # print request.user
    fullName = 0
    if not request.user.is_anonymous():
            fullName = Artist.objects.filter(user=request.user)
            fullName = fullName[0].name
    try:
        documents = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        documents = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        documents = paginator.page(paginator.num_pages)
    return render(request, 'bh2017/jury.html', {'documents': documents, 'formAuth': formAuth, 'Artist': fullName, 'jurys': jurys})

def sponsors(request):
    formAuth = UserAuth()
    fullName = 0
    if not request.user.is_anonymous():
            fullName = Artist.objects.filter(user=request.user)
            fullName = fullName[0].name
    return render(request, 'bh2017/sponsors.html', {'formAuth': formAuth, 'Artist': fullName})

def partners(request):
    form = ArtistForm()
    formAuth = UserAuth()
    obj = Partner.objects.all()
    fullName = 0
    if not request.user.is_anonymous():

bh2017/templates/bh2017/final_gallery.html
{% extends 'bh2017/base.html'%}
{% load staticfiles %}

{% block title %} Всероссийская битва художников {% endblock %}
{% block sidebar %}
    <ul id="sidebarList">
                <li><a class="menuNone" href="{% url 'bh2017:registration' %}">РЕГИСТРАЦИЯ</a></li>
                <li><a class="menuSelected" href="{% url 'bh2017:com_gallerys' %}">ГАЛЕРЕЯ</a></li>
                <li><a class="menuNone" href="{% url 'bh2017:tasks' %}">ЗАДАНИЯ</a></li>
                <li><a class="menuNone" href="{% url 'bh2017:prizes' %}">ПРИЗЫ</a></li>
                <li><a class="menuNone" href="{% url 'bh2017:rules' %}">ПРАВИЛА</a></li>
                <li><a class="menuNone" href="{% url 'bh2017:jury' %}">ЖЮРИ</a></li>
                <li><a class="menuNone" href="{% url 'bh2017:sponsors' %}">СПОНСОРЫ</a></li>
                <li><a class="menuNone" href="{% url 'bh2017:partners' %}">ПАРТНЕРЫ</a></li>
                <li><a class="menuNone" href="{% url 'bh2017:faq' %}">ВОПРОСЫ-ОТВЕТЫ</a></li>
            </ul>
{% endblock %}
{% block content %}
<div id="contentWrap">
    <h2><a href="{% url 'bh2017:loginJury' %}">Назад к галереям</a></h2>
{% if user and not user.is_anonymous %}
            {% if documents %}

                <ul id = "final_gallery_list">
                {% for document, i, t1, t2, t3, t4, t5, t6, t7 in listOfTrue %}
                    <h1>Работы участника № {{ document.id }}</h1>
                    <li class="final_gallery_list_dot">
                        <ul class="final_gallery_list_dot_list">
                            {% if t1 %}
                            <li class="final_gallery_list_dot_list_dot"><div class="galleryImgWrap"><img id="{{ t1.id }}" src="{{ t1.url }}" alt="Reducto!" class="partnerLogo"></div></li>
                            {% endif %}
                            {% if t2 %}
                            <li class="final_gallery_list_dot_list_dot"><div class="galleryImgWrap"><img id="{{ t2.id }}" src="{{ t2.url }}" alt="Reducto!" class="partnerLogo"></div></li>
                            {% endif %}
                            {% if t3 %}
                            <li class="final_gallery_list_dot_list_dot"><div class="galleryImgWrap"><img id="{{ t3.id }}" src="{{ t3.url }}" alt="Reducto!" class="partnerLogo"></div></li>
                            {% endif %}
                            {% if t4 %}
                            <li class="final_gallery_list_dot_list_dot"><div class="galleryImgWrap"><img id="{{ t4.id }}" src="{{ t4.url }}" alt="Reducto!" class="partnerLogo"></div></li>
                            {% endif %}
                            {% if t5 %}
                            <li class="final_gallery_list_dot_list_dot"><div class="galleryImgWrap"><img id="{{ t5.id }}" src="{{ t5.url }}" alt="Reducto!" class="partnerLogo"></div></li>
                            {% endif %}
                            {% if t6 %}
                            <li class="final_gallery_list_dot_list_dot"><div class="galleryImgWrap"><img id="{{ t6.id }}" src="{{ t6.url }}" alt="Reducto!" class="partnerLogo"></div></li>
                            {% endif %}
                            {% if t7 %}
                            <li class="final_gallery_list_dot_list_dot"><div class="galleryImgWrap"><img id="{{ t7.id }}" src="{{ t7.url }}" alt="Reducto!" class="partnerLogo"></div></li>
                            {% endif %}
                            <li class="galleryDotListDot"><div>{{ document.votess }}<span> голосов - </span>
                            {% if i %}
                                <a class="Vote" href="{% url 'bh2017:final_vote' document.id %}">Убрать голос</a>
                            {% else %}
                                <a class="remVote" href="{% url 'bh2017:final_remVote' document.id %}">Проголосовать</a>
                            {% endif %}
                            </div></li>
                        </ul>
                    </li>
                {% endfor %}
                </ul>
            <div id="more">
            {% if documents.has_previous %}
            <a class="prewButton" href="?page=1"> На первую </a>
            <a class="prewButton" href="?page={{ documents.previous_page_number }}"> << Предыдущая | </a>
            {% endif %}
            <span id="currentPage"> Страница {{ documents.number }} из {{ documents.paginator.num_pages }} </span>
            {% if documents.has_next %}
                <a class="nextButton" href="?page={{ documents.next_page_number }}"> | Следующая >></a>
                <a class="nextButton" href="?page={{ documents.paginator.num_pages }}"> На последнюю </a>
            {% endif %}
            </div>
            {% else %}
                <h2>Ни одной работы еще не загрузили.</h2>
            {% endif %}
        {% else %}
            <div id="wrongPass">
            <h1>УВАЖАЕМЫЕ ЖЮРИ, ВВЕДИТЕ ЛОГИН И ПАРОЛЬ</h1>
            </div>
        <div id="formAuthWrapWrap">
        <div id="formAuthWrap">
            <form action="{% url 'bh2017:AuthJury' %}" method="POST" enctype="multipart/form-data">
                <p>{% csrf_token %}</p>
                <ul id="formAuthList">
                    <li>{{ juryAuth.username }}</li>
                    <li>{{ juryAuth.password }}</li>
                 </ul>
                <ul id="loginButList">
                    <li class="loginButListDot">
                        <div id="loginBut">
                            <input type="submit" value="ВОЙТИ" />
                        </div>
                    </li>
                </ul>
            </form>
        </div>
        </div>
        {% endif %}
</div>
{% endblock %}
{% block partner%}
{% endblock %}

bh2017/templates/bh2017/jury.html
{% extends 'bh2017/base.html'%}
{% load staticfiles %}

{% block title %} Всероссийская битва художников {% endblock %}
{% block sidebar %}
    <ul id="sidebarList">
                <li><a class="menuNone" href="{% url 'bh2017:registration' %}">РЕГИСТРАЦИЯ</a></li>
        <li><a class="menuNone" href="{% url 'bh2017:com_gallerys' %}">ГАЛЕРЕЯ</a></li>
                <li><a class="menuNone" href="{% url 'bh2017:tasks' %}">ЗАДАНИЯ</a></li>
                <li><a class="menuNone" href="{% url 'bh2017:prizes' %}">ПРИЗЫ</a></li>
                <li><a class="menuNone" href="{% url 'bh2017:rules' %}">ПРАВИЛА</a></li>
                <li><a class="menuSelected" href="{% url 'bh2017:jury' %}">ЖЮРИ</a></li>
                <li><a class="menuNone" href="{% url 'bh2017:sponsors' %}">СПОНСОРЫ</a></li>
                <li><a class="menuNone" href="{% url 'bh2017:partners' %}">ПАРТНЕРЫ</a></li>
                <li><a class="menuNone" href="{% url 'bh2017:faq' %}">ВОПРОСЫ-ОТВЕТЫ</a></li>
            </ul>
{% endblock %}
{% block content %}
    <div id="contentWrap">
        <a href="{% url 'bh2017:index' %}"><img id="logoother" src="{% static 'bh2017/images/logoother.jpg' %}"></a>
        <h1>ЖЮРИ КОНКУРСА</h1>
        {% if jurys %}
            <ul id="jurysList">
                {% for jury in jurys%}
                <li class="jurysListDot">
                    <ul class="jurysListDotList">
                        <li class="juryImg">
                            <div class="juryImgWrap">
                                <img id="jury.id" src="{{ jury.docfile.url }}" alt="Reducto!" class="partnerLogo">
                            </div>
                        </li>
                        <li class="juryText">
                            <ul class="juryTextWrap">
                                <li class="juryName">
                                    <span>{{ jury.name }}</span>
                                </li>
                                <li class="juryTitle">
                                    <span>{{ jury.text }}</span>
                                </li>
                                <li class="juryPost">
{{ jury.Post2|safe }}
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

bh2017/templates/bh2017/thankyou.html
{% extends 'bh2017/base.html'%}
{% load staticfiles %}

{% block title %} Всероссийская битва художников {% endblock %}

{% block content %}
    <div id="contentWrap">
        <h1>Большое спасибо, мы отправили вам на почту ваш пароль.</h1>
    </div>
{% endblock %}